### ISSUE TITLE
Set up continuous deployment of Relaynet-Internet Gateway to a production environment

### ISSUE THREAD

**Issue by gnarea** [relaycorp/cloud-gateway#5]
Output: https://github.com/relaycorp/cloud-gateway

# TODO

- [x] Merge `*-chart` repos into respective app repos.
- [x] Recreate test env to ensure everything works.
- Authenticate with Vault using Kubernetes service accounts:
  - [x] Log in with the pod's service account credentials: https://www.vaultproject.io/docs/auth/kubernetes
  - [x] Renew the token periodically: https://www.vaultproject.io/api-docs/auth/token#renew-a-token
- [x] Reinstate TLS in Stan-Postgres connections
- [x] Make GKE cluster regional (requires destroying the whole environment).
- [x] Move secrets shared with CF from k8s to GCP secrets manager: https://cloud.google.com/secret-manager
- [x] helmfile: use apply instead of sync. Require helm-diff. See: https://github.com/roboll/helmfile/issues/1134
- [x] Stan pipleine: Don't leak DB password
- [x] Right-size cluster
- [x] Set requests and limits on each pod
- [x] Set replicas for each component
- [x] Split up the monolithic Terraform module into one module per environment.
- [x] NATS: Configure TTL for each channel.
- [x] Replace BackendConfig CRD with Terraform resource
- [x] Replace managed certificate CRD with TF resource
- [x] Integrate `helmfile diff` on PRs.
- [x] Enable clustering in NATS Streaming
- [x] Set up anti-affinity for each service
- [x] Gateway: checksum of CMs/secrets.
- [x] Set gateway key in values file
